### ISSUE TITLE
The motivating use case

### ISSUE THREAD

**Issue by Viir** [elm-lang/cookie#10]
In the case I found, I wanted to know if a user has been using my app the day before. To make this connection between different sessions, I use webbrowser cookies.

I tried the approach of using the `Set-Cookie` header on an HTTP response. It turned out in that case at least googles chrome browser does not send the cookie with future http requests to the same URL.

Because of this limitation of http cookies, I now use Native code to read and write the cookie.

**Comment by zwilias** [comment]
@Viir no need for native; the [`withCredentials` flag on Http.request](http://package.elm-lang.org/packages/elm-lang/http/1.0.0/Http#request) enables exactly this use-case: persistence of information on the client without your app having direct access to it.

**Comment by Viir** [comment]
@zwilias, thank you, this is very interesting. I will try using `withCredentials` to make cookies work with HTTP.

**Comment by Viir** [comment]
Setting the `withCredentials` flag on the HTTP requests made the browser send the cookies, so I consider this issue solved.
