### ISSUE TITLE
Serverless backends

### ISSUE THREAD

**Issue by robinheghan** [elm-lang/cookie#2]
My backend is currently using AWS Lambda, where I don't have the option of setting HTTP-headers. Lambda is just JSON in and JSON out. Currently I'm solving this by returning a session token as part of the JSON response, and then making sure to pass that token on every HTTP request, but being able to set a cookie locally would be a better option.

**Comment by evancz** [comment]
Interesting case! Without further information my first questions would be:
1. Could you add a snippet like `<script>document.cookie = 'token=abc123';</script>` to whatever pages you are serving to users?
2. Shouldn't AWS Lambda let people use the `Set-Cookie` header in particular?

I guess this depends on whether you are serving pages from one domain, but requests are going out to AWS Lambda on some other domain. Also, if this platform is "just JSON in and JSON out" as you say, how would you have access to the `Cookie` header anyway? Wouldn't that do nothing for you even if it was set?

**Comment by robinheghan** [comment]
Aight. After some searching I discovered that you can set the cookie header from aws lambda (technically through api gateway, which allows you to create a http frontend for lambda).

So never mind. The documentation for AWS is horrible, so I missed this.
